const practiceArr = [
{
	unit: 'Unit-1',
	exampleExercise: [`<p class="practice-test__text">Potatoes <input class="practice-exercise__empty">  big</p>`,
	`<p class="practice-test__text">I <input class="practice-exercise__empty"> eat fish</p>`,
	`<p class="practice-test__text">He  <input class="practice-exercise__empty"> have a car</p>`,
	`<p class="practice-test__text">We  <input class="practice-exercise__empty"> the best</p>`,
	`<p class="practice-test__text"> <input class="practice-exercise__empty">  you a doctor</p>`,
	],
	exampleTest: [`<p class="practice-test__text">Potatoes  <span class="practice-test__empty"></span>  big</p>`,
	`<p class="practice-test__text">I  <span class="practice-test__empty"></span> eat fish</p>`,
	`<p class="practice-test__text">He  <span class="practice-test__empty"></span> have  a car</p>`,
	`<p class="practice-test__text">We  <span class="practice-test__empty"></span> the best</p>`,
	`<p class="practice-test__text"><span class="practice-test__empty"></span>  you a doctor</p>`,
	],
	answerAll: ['am','are','is','was','were','do','did','doesn\'t','can','don\'t','may','must'],
	answerCorrect: ['are', 'don\'t', 'doesn\'t', 'are', 'are'],
},
{
	unit: 'Unit-2',
	exampleExercise: [`<p class="practice-test__text">I <input class="practice-exercise__empty">  a student</p>`,
	`<p class="practice-test__text">They  <input class="practice-exercise__empty"> in London</p>`,
	`<p class="practice-test__text"><input class="practice-exercise__empty">you in the supermarket?</p>`,
	`<p class="practice-test__text"><input class="practice-exercise__empty">she a teacher?</p>`,
	`<p class="practice-test__text">I <input class="practice-exercise__empty">play tennis yesterday</p>`,
	`<p class="practice-test__text">We <input class="practice-exercise__empty">see her at weekend</p>`,
	`<p class="practice-test__text"><input class="practice-exercise__empty">you watch TV last week?</p>`,
	],
	exampleTest: [`<p class="practice-test__text">I  <span class="practice-test__empty"></span>  a student</p>`,
	`<p class="practice-test__text">They  <span class="practice-test__empty"></span> in London</p>`,
	`<p class="practice-test__text"><span class="practice-test__empty"></span>you in the supermarket?</p>`,
	`<p class="practice-test__text"><span class="practice-test__empty"></span>she a teacher?</p>`,
	`<p class="practice-test__text">I <span class="practice-test__empty"></span>play tennis yesterday</p>`,
	`<p class="practice-test__text">We<span class="practice-test__empty"></span>see her at weekend</p>`,
	`<p class="practice-test__text"><span class="practice-test__empty"></span>you watch TV last week?</p>`,
	],
	answerAll: ['am','are','is','was','were','do','did','doesn\'t','don\'t','didn\'t'],
	answerCorrect: ['was', 'were', 'were', 'was','didn\'t','didn\'t','did'],
},

];